### ISSUE TITLE
Antis #Dont Work

### ISSUE THREAD

**Issue by AnythingForTheTrustRank** [ScottGriffin213/BundleBouncer#3]
### What OS are you using?

bofa

### VRChat Information

https://discord.gg/Stw39t5b3r 

Legit bypasses to your mod publicly, with avatar ids rotating every 5 hours 0 / / / / 0

### Bug Description

It died to AAXX, the only antis that worked were the ones spoonfed by azurilex. #rip my nigga

### Reproduction Steps

get better

### Expected Behaviour

getting better

### Actual Behaviour

null should learn how to reverse engineer without relying on other people

### Logs

https://hex-rays.com/ida-pro/

### All of the following criteria must be met

- [X] I have installed all the <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">MelonLoader requirements</a>.
- [X] Full, unedited ``Latest.log`` is attached
- [X] I have listed what, if any, clients I am using.
- [X] I realize that the devs have other things going on and may take time to respond.
- [X] I have written and proofread my report so that I don't sound like a jerk.
- [X] I am not reporting a new/incorrect crasher, since github isn't the place for that.

**Comment by ScottGriffin213** [comment]
Cool story bro

Also null contributed UI code, not reversing stuff.
